# Generated by Django 4.0.4 on 2022-07-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_alter_userp_customer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='b_pic',
            field=models.ImageField(blank=True, upload_to='books/%Y/%m/%d/'),
        ),
    ]
