# Generated by Django 4.0.4 on 2022-07-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_alter_addbook_b_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='customer_picture',
            field=models.ImageField(blank=True, upload_to='profile/%Y/%m/%d/'),
        ),
    ]
